version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pitch_enhancer
    ports:
      - '5432:5432'
    volumes:
      - ./local_database:/var/lib/postgresql/data
